export type Technique = { id: string; name: string; subtitle: string; feet: string; legs: string; torso: string; arms: string; errors: string; drill: string; david?: string }
export const techniques: Technique[] = [
  { id: 'yoi', name: 'Yoi', subtitle: 'Se préparer, sans se crisper', feet: 'Position de préparation : appuis stables, écartement naturel proche du bassin. L’ouverture exacte des pieds dépend du yoi enseigné au club.', legs: 'Genoux disponibles, sans les verrouiller. Répartir le poids sans basculer sur les pointes.', torso: 'Buste vertical, nuque longue, regard devant. Garder la tête à sa hauteur naturelle, sans lever le menton.', arms: 'Épaules basses ; placer les mains comme David le montre pour cet exercice.', errors: 'Se raidir, hausser les épaules, retenir son souffle ou regarder ses pieds.', drill: 'Prendre la position, respirer trois fois et relâcher. Refaire trois fois.' },
  { id: 'junzuki-dachi', name: 'Junzuki dachi', subtitle: 'Deux rails pour construire les appuis', feet: 'Un pied devant, l’autre derrière et décalé latéralement : jamais sur une ligne unique. Pied avant dirigé vers l’action ; ouverture du pied arrière à régler avec David. Ne pas imposer de centimètres universels.', legs: 'Genou avant fléchi dans l’axe du pied. Jambe arrière allongée mais non verrouillée ; conserver la souplesse demandée en Wado. Raccourcir la position si le bassin ou les appuis se déforment.', torso: 'Buste redressé, bassin soutenu sans cambrure forcée. Tête stable, regard horizontal ; éviter de monter et descendre à chaque pas.', arms: 'Épaules détendues. Pour isoler les appuis, poser d’abord les mains sur les hanches.', errors: 'Marcher sur un fil, genou qui rentre, talon qui se soulève, pas trop long, tête penchée vers le sol.', drill: 'Placer deux repères parallèles au sol. Faire trois pas lents, vérifier les appuis à chaque arrivée, puis recommencer de l’autre côté.', david: 'Les deux pieds sont sur deux lignes, comme sur deux rails, et non sur une seule.' },
  { id: 'junzuki', name: 'Junzuki', subtitle: 'Avancer et frapper du même côté', feet: 'Avancer le pied du côté du poing qui frappe. Retrouver les deux rails à l’arrivée.', legs: 'Recevoir le poids avec le genou avant aligné ; garder la jambe arrière disponible sans verrouillage.', torso: 'Déplacer le corps avec le pas, sans jeter la tête ou le buste en avant. Coordonner l’arrivée des appuis et du poing.', arms: 'Poignet dans l’axe de l’avant-bras. Le poing avance vers la cible convenue ; l’autre bras revient en hikite selon la consigne du club. Garder une marge au coude à vide.', errors: 'Frapper seulement avec l’épaule, coude verrouillé, poignet cassé, pieds alignés ou souffle bloqué.', drill: 'Trois avancées lentes à hauteur moyenne, sans impact. S’arrêter après chaque pas pour vérifier l’équilibre.' },
  { id: 'gedan-barai', name: 'Gedan Barai', subtitle: 'Préparer puis balayer vers le bas', feet: 'Installer les appuis correspondant à l’exercice ; conserver la largeur des rails dans les déplacements en junzuki dachi.', legs: 'Genoux souples. Pendant un pivot, tourner les pieds avec le corps sans tordre un genou sur un pied bloqué.', torso: 'Rester redressé, regarder vers la nouvelle direction avant de terminer le mouvement. Ne pas plonger la tête.', arms: 'Préparer le bras devant le haut du corps, puis balayer vers le bas et l’extérieur. L’autre main revient en hikite. Faire préciser le croisement et le point d’arrivée par David.', errors: 'Grand moulinet, épaule levée, coude verrouillé ou rotation faite seulement avec les bras.', drill: 'Cinq préparations et balayages lents de chaque côté, d’abord sur place puis avec un seul pas.' },
  { id: 'mae-geri', name: 'Mae Geri', subtitle: 'Monter, déplier, replier, reposer', feet: 'Pied d’appui stable. Pour une frappe avec l’avant du pied, relever les orteils ; valider la surface de contact avec David avant tout travail sur cible.', legs: 'Monter le genou devant, déplier sans claquer l’articulation, replier, puis reposer avec contrôle. Genou d’appui légèrement souple.', torso: 'Buste stable et regard devant ; ne pas chercher la hauteur en se penchant fortement en arrière. Commencer bas.', arms: 'Garder les mains à la position demandée et les épaules relâchées ; éviter les grands mouvements de bras pour compenser.', errors: 'Jambe lancée sans retour, genou verrouillé, perte d’équilibre ou recherche de hauteur avant le contrôle.', drill: 'Avec une main près d’un mur, cinq montées de genou puis trois petits coups de pied lents par jambe, sans impact.' },
  { id: 'first-basic-kata', name: 'First Basic Kata', subtitle: 'Version du club à confirmer avec David', feet: 'Après chaque changement de direction, reconstruire les deux rails. Le tracé et l’ordre exact restent à confirmer : un souvenir de T ou de carré ne suffit pas à identifier la version.', legs: 'Réutiliser les appuis travaillés en cours, avec le genou avant aligné et sans torsion dans les pivots.', torso: 'Regarder dans la direction de l’action, tourner avec les appuis et conserver une hauteur de tête régulière.', arms: 'Réviser séparément Gedan Barai et Junzuki. Les techniques et leur ordre peuvent varier selon la forme débutante enseignée.', errors: 'Mélanger plusieurs vidéos, assimiler automatiquement ce kata à Taikyoku Shodan ou mémoriser un ordre non confirmé.', drill: 'Répéter seulement un fragment déjà validé au dojo, lentement. Noter le pied de départ, le sens du pivot et la technique avant d’ajouter la suite.', david: undefined },
]

export const preparation = [
  { name: 'Split squat', dose: '1 série de 5 par côté', cue: 'Pieds sur deux rails, descendre peu et lentement, genou dans l’axe.', easier: 'Tenir une chaise stable et réduire l’amplitude.' },
  { name: 'Maintien en fente', dose: '10 à 15 secondes par côté', cue: 'Position courte, buste vertical, respirer sans verrouiller les genoux.', easier: 'Remonter et rapprocher les pieds.' },
  { name: 'Mollets', dose: '8 montées contrôlées', cue: 'Monter sur les pointes puis redescendre doucement, poids réparti.', easier: 'Garder les deux mains sur un support stable.' },
  { name: 'Équilibre sur une jambe', dose: '15 secondes par côté', cue: 'Regard fixe, genou d’appui souple, bassin stable.', easier: 'Garder un doigt au mur ou les orteils libres au sol.' },
  { name: 'Montées de genou', dose: '5 par côté', cue: 'Lever, marquer une pause, reposer sans basculer le buste.', easier: 'Lever moins haut avec un appui au mur.' },
  { name: 'Dead bug', dose: '5 alternances par côté', cue: 'Sur le dos, déplacer lentement bras et jambe opposés sans creuser le bas du dos ; expirer.', easier: 'Garder les bras au sol et faire glisser un talon à la fois.' },
  { name: 'Squat contrôlé', dose: '6 répétitions lentes', cue: 'Descendre dans une amplitude confortable, genoux dans l’axe des pieds, puis remonter.', easier: 'S’asseoir doucement sur une chaise stable puis se relever.' },
]

export const sources = [
  { title: 'Techniques de base Wado : Junzuki, Gedan Barai et Mae Geri (Karaté Tempo Gouvieux)', url: 'https://karate-tempo-gouvieux.jimdofree.com/le-wado-ryu/techniques-de-base/' },
  { title: 'Positions Wado : photos et repères', url: 'https://www.dojoupdate.com/wado-ryu-stances/' },
  { title: 'First Basic Kata : ressource illustrée, version à comparer au cours', url: 'https://www.dojoupdate.com/wado-ryu-katas/first-basic-kata/' },
  { title: 'Wadō-ryū USA : diversité des formes débutantes', url: 'https://wadoryuusa.com/kata/' },
  { title: 'Histoire : fédération Wado-Ryu (PDF en anglais)', url: 'https://www.wado-ryu.jp/en/data/about.pdf' },
]

export const ukeResources = [
  { id: 'defenses', title: 'Les défenses Wado-Ryu en images', publisher: 'Bushido Karaté Carros', format: 'Images · français', url: 'https://bushidokaratecarros.fr/Techniques/defenses/defensesdetails.html', description: 'Une galerie pour reconnaître les uke : défense haute, balayage bas, défenses circulaires et mains ouvertes.', observe: 'Comparer la préparation du bras et sa position finale. Chercher le nom de la technique sur la page.' },
  { id: 'basics', title: 'Cinq uke parmi les techniques de base', publisher: 'Karaté Tempo Gouvieux', format: 'Images · français', url: 'https://karate-tempo-gouvieux.jimdofree.com/le-wado-ryu/techniques-de-base/', description: 'La rubrique « UKE (Défenses) » rassemble Gedan Barai, Jodan Age Uke, Soto Uke, Uchi Uke et Shuto Uke.', observe: 'Observer aussi les pieds : une position de bras seule ne raconte pas tout le mouvement.' },
  { id: 'lexicon', title: 'Retrouver les mots entendus au dojo', publisher: 'Wado-Osny', format: 'Lexique · français', url: 'https://wado-osny.fr/lexique-technique/', description: 'Les défenses, les niveaux du corps et les déplacements sont réunis dans un lexique court.', observe: 'Associer le nom japonais au geste montré par David, puis le noter dans sa fiche.' },
  { id: 'syllabus', title: 'Soto / Uchi : comparer les appellations', publisher: 'Bridgwater Bushi Karate Club', format: 'Programme de club · anglais', url: 'https://www.bushi.org.uk/club-grade-syllabus/', description: 'Ce club emploie Soto pour une défense vers l’extérieur et Uchi vers l’intérieur, contrairement aux descriptions de Carros.', observe: 'Une aide pour comprendre les différences de vocabulaire, pas le programme de grades de ton dojo.' },
  { id: 'kata-videos', title: 'Observer les défenses dans les kata Pinan', publisher: 'Bridgwater Bushi Karate Club', format: 'Vidéos externes · page en anglais', url: 'https://www.bushi.org.uk/videos/', description: 'La page propose notamment les cinq Pinan, présentés comme exécutés par Fukazawa Sensei.', observe: 'Choisir un kata déjà abordé au cours et repérer les changements de direction. Ce ne sont pas des tutoriels isolés de chaque uke.' },
]

export const ukeGuides = [
  { id: 'gedan-barai', name: 'Gedan Barai', level: 'Bas · gedan', cue: 'Un balayage descendant', watch: 'La préparation, la descente de l’avant-bras et le retour de l’autre main.', sources: ['defenses', 'basics'] },
  { id: 'jodan-age-uke', name: 'Jodan Age Uke', level: 'Haut · jodan', cue: 'Une défense montante', watch: 'Le trajet qui monte devant le corps et la position finale de l’avant-bras par rapport au front.', sources: ['defenses', 'basics'] },
  { id: 'soto-uke', name: 'Soto Uke', level: 'Moyen · chudan', cue: 'Une défense circulaire de l’avant-bras', watch: 'Le sens du trajet utilisé au dojo : les noms Soto/Uchi ne suffisent pas à le déduire dans toutes les sources.', sources: ['defenses', 'syllabus'] },
  { id: 'uchi-uke', name: 'Uchi Uke', level: 'Moyen · chudan', cue: 'L’autre trajet circulaire à distinguer', watch: 'Le point de départ, le passage devant le buste et le point d’arrivée ; comparer avec Soto appris au cours.', sources: ['defenses', 'syllabus'] },
  { id: 'shuto-uke', name: 'Shuto Uke', level: 'Main ouverte', cue: 'Le tranchant de la main', watch: 'La main ouverte, le poignet et le placement de l’autre main. La position des jambes dépend de l’exercice.', sources: ['defenses', 'basics'] },
  { id: 'nagashi-uke', name: 'Nagashi Uke', level: 'Accompagnement', cue: 'Dévier en accompagnant', watch: 'Le lien entre la main ou l’avant-bras et le déplacement du corps ; le timing se travaille au dojo.', sources: ['defenses', 'lexicon'] },
]

techniques.push(
  { id: 'jodan-age-uke', name: 'Jodan Age Uke', subtitle: 'Faire monter la défense, garder le regard disponible', feet: 'Prendre la position demandée au cours. Commencer sur place pour isoler le trajet du bras.', legs: 'Garder les genoux disponibles ; éviter de se grandir sur les pointes pendant la montée du bras.', torso: 'Conserver le regard devant, sans rentrer la tête ni incliner le buste pour suivre la main.', arms: 'L’avant-bras monte pour réaliser la défense haute. Reproduire la préparation, l’inclinaison finale et la place de l’autre main montrées par David.', errors: 'Hausser l’épaule, cacher tout son regard derrière le bras ou chercher une grande amplitude sans contrôle.', drill: 'Proposition de révision : trois répétitions lentes de chaque côté, puis une pause à la position finale pour comparer avec la consigne du cours.' },
  { id: 'soto-uke', name: 'Soto Uke', subtitle: 'Identifier le trajet avant de mémoriser le nom', feet: 'Garder les appuis de l’exercice appris ; travailler sur place avant d’ajouter un pas.', legs: 'Rester stable pendant la rotation, sans entraîner le genou vers l’intérieur.', torso: 'Laisser le buste participer comme au cours, sans tourner seulement l’épaule ni se pencher.', arms: 'Défense circulaire de l’avant-bras. Carros décrit un trajet de l’extérieur vers l’intérieur ; Bushi emploie Soto pour le trajet vers l’extérieur. Retenir le trajet montré par David et le noter ci-dessous.', errors: 'Copier un trajet trouvé en ligne en se fiant seulement au nom, lever le coude ou aller au-delà de la position montrée.', drill: 'Proposition de révision : nommer le départ et l’arrivée de la main, puis refaire trois fois le trajet validé au cours, sans impact.' },
  { id: 'uchi-uke', name: 'Uchi Uke', subtitle: 'Distinguer les deux défenses circulaires', feet: 'Utiliser les mêmes appuis que pour la comparaison avec Soto, afin de se concentrer sur les bras.', legs: 'Conserver une légère souplesse et répartir le poids sans basculer pendant le geste.', torso: 'Garder la tête stable et l’épaule détendue. La rotation du corps suit la consigne du dojo.', arms: 'Carros décrit Uchi de l’intérieur vers l’extérieur ; Bushi utilise Uchi pour le trajet vers l’intérieur. Observer le départ, le passage du coude et l’arrivée dans la démonstration de David.', errors: 'Intervertir Uchi et Soto entre deux vidéos, ouvrir le bras trop loin ou tourner le poignet pour compenser.', drill: 'Proposition de révision : alterner une répétition de Soto et une de Uchi tels qu’appris au dojo ; marquer une pause et annoncer le nom à chaque fois.' },
  { id: 'shuto-uke', name: 'Shuto Uke', subtitle: 'Une main ouverte, un poignet contrôlé', feet: 'Prendre la position montrée avec cette technique ; ne pas supposer que toutes les démonstrations utilisent les mêmes appuis.', legs: 'Rester à une hauteur confortable, sans chercher une posture basse avant de contrôler le geste.', torso: 'Maintenir le buste redressé et les épaules disponibles.', arms: 'La défense utilise le tranchant de la main. Reprendre l’ouverture de la main, l’orientation du poignet et le placement du bras opposé enseignés au cours.', errors: 'Raidir les doigts et les épaules, casser le poignet ou oublier l’autre main.', drill: 'Proposition de révision : trois préparations lentes par côté, puis trois gestes complets sans contact. Vérifier les deux mains à chaque arrêt.' },
  { id: 'nagashi-uke', name: 'Nagashi Uke', subtitle: 'Accompagner la déviation', feet: 'Reprendre uniquement le déplacement déjà démontré au dojo ; commencer petit et lent.', legs: 'Tourner ou déplacer les appuis avec le corps, sans laisser le genou pivoter sur un pied bloqué.', torso: 'Observer comment le corps se place par rapport à la ligne de l’attaque dans la démonstration du professeur.', arms: 'La main ou l’avant-bras accompagne la déviation. Le point de contact et le moment d’action se règlent avec David ; un dessin ne permet pas de vérifier le timing.', errors: 'Chercher à arrêter en force, faire un grand geste de bras ou séparer complètement le déplacement de la défense.', drill: 'Proposition de révision : à vide, répéter trois fois le déplacement appris avec son geste de main. Réserver le travail de distance avec partenaire au cours.' },
)
