export type Technique = { id: string; name: string; subtitle: string; feet: string; legs: string; torso: string; arms: string; errors: string; drill: string; david?: string }
export const techniques: Technique[] = [
  { id: 'yoi', name: 'Yoi', subtitle: 'Se préparer, sans se crisper', feet: 'Position de préparation : appuis stables, écartement naturel proche du bassin. L’ouverture exacte des pieds dépend du yoi enseigné au club.', legs: 'Genoux disponibles, sans les verrouiller. Répartir le poids sans basculer sur les pointes.', torso: 'Buste vertical, nuque longue, regard devant. Garder la tête à sa hauteur naturelle, sans lever le menton.', arms: 'Épaules basses ; placer les mains comme David le montre pour cet exercice.', errors: 'Se raidir, hausser les épaules, retenir son souffle ou regarder ses pieds.', drill: 'Prendre la position, respirer trois fois et relâcher. Refaire trois fois.' },
  { id: 'junzuki-dachi', name: 'Junzuki dachi', subtitle: 'Deux rails pour construire les appuis', feet: 'Un pied devant, l’autre derrière et décalé latéralement : jamais sur une ligne unique. Pied avant dirigé vers l’action ; ouverture du pied arrière à régler avec David. Ne pas imposer de centimètres universels.', legs: 'Genou avant fléchi dans l’axe du pied. Jambe arrière allongée mais non verrouillée ; conserver la souplesse demandée en Wado. Raccourcir la position si le bassin ou les appuis se déforment.', torso: 'Buste redressé, bassin soutenu sans cambrure forcée. Tête stable, regard horizontal ; éviter de monter et descendre à chaque pas.', arms: 'Épaules détendues. Pour isoler les appuis, poser d’abord les mains sur les hanches.', errors: 'Marcher sur un fil, genou qui rentre, talon qui se soulève, pas trop long, tête penchée vers le sol.', drill: 'Placer deux repères parallèles au sol. Faire trois pas lents, vérifier les appuis à chaque arrivée, puis recommencer de l’autre côté.', david: 'Les deux pieds sont sur deux lignes, comme sur deux rails, et non sur une seule.' },
  { id: 'junzuki', name: 'Junzuki', subtitle: 'Avancer et frapper du même côté', feet: 'Avancer le pied du côté du poing qui frappe. Retrouver les deux rails à l’arrivée.', legs: 'Recevoir le poids avec le genou avant aligné ; garder la jambe arrière disponible sans verrouillage.', torso: 'Déplacer le corps avec le pas, sans jeter la tête ou le buste en avant. Coordonner l’arrivée des appuis et du poing.', arms: 'Poignet dans l’axe de l’avant-bras. Le poing avance vers la cible convenue ; l’autre bras revient en hikite selon la consigne du club. Garder une marge au coude à vide.', errors: 'Frapper seulement avec l’épaule, coude verrouillé, poignet cassé, pieds alignés ou souffle bloqué.', drill: 'Trois avancées lentes à hauteur moyenne, sans impact. S’arrêter après chaque pas pour vérifier l’équilibre.' },
  { id: 'gedan-barai', name: 'Gedan Barai', subtitle: 'Préparer puis balayer vers le bas', feet: 'Installer les appuis correspondant à l’exercice ; conserver la largeur des rails dans les déplacements en junzuki dachi.', legs: 'Genoux souples. Pendant un pivot, tourner les pieds avec le corps sans tordre un genou sur un pied bloqué.', torso: 'Rester redressé, regarder vers la nouvelle direction avant de terminer le mouvement. Ne pas plonger la tête.', arms: 'Préparer le bras devant le haut du corps, puis balayer vers le bas et l’extérieur. L’autre main revient en hikite. Faire préciser le croisement et le point d’arrivée par David.', errors: 'Grand moulinet, épaule levée, coude verrouillé ou rotation faite seulement avec les bras.', drill: 'Cinq préparations et balayages lents de chaque côté, d’abord sur place puis avec un seul pas.' },
  { id: 'mae-geri', name: 'Mae Geri', subtitle: 'Monter, déplier, replier, reposer', feet: 'Pied d’appui stable. Pour une frappe avec l’avant du pied, relever les orteils ; valider la surface de contact avec David avant tout travail sur cible.', legs: 'Monter le genou devant, déplier sans claquer l’articulation, replier, puis reposer avec contrôle. Genou d’appui légèrement souple.', torso: 'Buste stable et regard devant ; ne pas chercher la hauteur en se penchant fortement en arrière. Commencer bas.', arms: 'Garder les mains à la position demandée et les épaules relâchées ; éviter les grands mouvements de bras pour compenser.', errors: 'Jambe lancée sans retour, genou verrouillé, perte d’équilibre ou recherche de hauteur avant le contrôle.', drill: 'Avec une main près d’un mur, cinq montées de genou puis trois petits coups de pied lents par jambe, sans impact.' },
  { id: 'first-basic-kata', name: 'First Basic Kata', subtitle: 'Version du club à confirmer avec David', feet: 'Après chaque changement de direction, reconstruire les deux rails. Le tracé et l’ordre exact restent à confirmer : un souvenir de T ou de carré ne suffit pas à identifier la version.', legs: 'Réutiliser les appuis travaillés en cours, avec le genou avant aligné et sans torsion dans les pivots.', torso: 'Regarder dans la direction de l’action, tourner avec les appuis et conserver une hauteur de tête régulière.', arms: 'Réviser séparément Gedan Barai et Junzuki. Les techniques et leur ordre peuvent varier selon la forme débutante enseignée.', errors: 'Mélanger plusieurs vidéos, assimiler automatiquement ce kata à Taikyoku Shodan ou mémoriser un ordre non confirmé.', drill: 'Répéter seulement un fragment déjà validé au dojo, lentement. Noter le pied de départ, le sens du pivot et la technique avant d’ajouter la suite.', david: undefined },
]

export const preparation = [
  { name: 'Split squat', dose: '1 série de 5 par côté', cue: 'Pieds sur deux rails, descendre peu et lentement, genou dans l’axe.', easier: 'Tenir une chaise stable et réduire l’amplitude.' },
  { name: 'Maintien en fente', dose: '10 à 15 secondes par côté', cue: 'Position courte, buste vertical, respirer sans verrouiller les genoux.', easier: 'Remonter et rapprocher les pieds.' },
  { name: 'Mollets', dose: '8 montées contrôlées', cue: 'Monter sur les pointes puis redescendre doucement, poids réparti.', easier: 'Garder les deux mains sur un support stable.' },
  { name: 'Équilibre sur une jambe', dose: '15 secondes par côté', cue: 'Regard fixe, genou d’appui souple, bassin stable.', easier: 'Garder un doigt au mur ou les orteils libres au sol.' },
  { name: 'Montées de genou', dose: '5 par côté', cue: 'Lever, marquer une pause, reposer sans basculer le buste.', easier: 'Lever moins haut avec un appui au mur.' },
  { name: 'Dead bug', dose: '5 alternances par côté', cue: 'Sur le dos, déplacer lentement bras et jambe opposés sans creuser le bas du dos ; expirer.', easier: 'Garder les bras au sol et faire glisser un talon à la fois.' },
  { name: 'Squat contrôlé', dose: '6 répétitions lentes', cue: 'Descendre dans une amplitude confortable, genoux dans l’axe des pieds, puis remonter.', easier: 'S’asseoir doucement sur une chaise stable puis se relever.' },
]

export const sources = [
  { title: 'Techniques de base Wado : Junzuki, Gedan Barai et Mae Geri (Karaté Tempo Gouvieux)', url: 'https://karate-tempo-gouvieux.jimdofree.com/le-wado-ryu/techniques-de-base/' },
  { title: 'Positions Wado : photos et repères', url: 'https://www.dojoupdate.com/wado-ryu-stances/' },
  { title: 'First Basic Kata : ressource illustrée, version à comparer au cours', url: 'https://www.dojoupdate.com/wado-ryu-katas/first-basic-kata/' },
  { title: 'Wadō-ryū USA : diversité des formes débutantes', url: 'https://wadoryuusa.com/kata/' },
  { title: 'Histoire : fédération Wado-Ryu (PDF en anglais)', url: 'https://www.wado-ryu.jp/en/data/about.pdf' },
]
